# Generated by Django 3.0.6 on 2020-07-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
